translation_api_key = 'YOUR GOOGLE TRANSLATE API KEY'
user_name = 'ACCOUNT NAME (NO @ SYMBOL)'
password = 'PASSWORD'
azure_key = 'YOUR AZURE KEY'
azure_location = 'YOUR AZURE LOCATION'
azure_endpoint = 'YOUR AZURE ENDPOINT'